name: Build Archives (CI Only)

on:
  push:
    branches:
      - '**'

jobs:
  build_archives:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare template files
        run: |
          python ./scripts/prepare_template.py

      - name: Prepare archives
        run: |
          python ./scripts/prepare_archives.py

      - name: Upload archives as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tutorial-archives
          path: |
            docs/data/gegelati-tutorial.zip
            docs/data/gegelati-tutorial-solution.zip
            docs/data/gegelati-tutorial-strengthening-solution.zip
            docs/data/gegelati-tutorial-parallel-solution.zip

  test_archives:
    needs: build_archives
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        archive:
          - gegelati-tutorial.zip
          - gegelati-tutorial-solution.zip
          - gegelati-tutorial-strengthening-solution.zip
          - gegelati-tutorial-parallel-solution.zip
        os: [ubuntu-latest, windows-latest] ##, windows-latest, macos-latest]
        compiler: [gcc, msvc] ##, clang, msvc]
        gegelati_version: [master, develop]
        # Use trick to deactivate develop build on main branch only.
        isMain:
          - ${{ contains(github.ref, 'main') }}
        exclude:
          # Exclude develop build on main branch
          - isMain: true
            gegelati_version: develop
          # Exclude MSVC on non-Windows
          - os: ubuntu-latest
            compiler: msvc
          ## - os: macos-latest
          ##  compiler: msvc
          # Exclude clang on Windows (for now)
          - os: windows-latest
            compiler: clang
          ## - os: windows-latest
          ##   compiler: clang

    name: Test ${{ matrix.archive }} on ${{ matrix.os }} with ${{ matrix.compiler }} and Gegelati ${{ matrix.gegelati_version }}
    env:
      CMAKE_GENERATOR: ${{ matrix.compiler == 'msvc' && 'Visual Studio 17 2022' || matrix.compiler == 'gcc' && matrix.os == 'windows-latest' && 'MinGW Makefiles' || 'Unix Makefiles'}}
    steps:
      - uses: actions/checkout@v3

      - name: Download archives artifact
        uses: actions/download-artifact@v4
        with:
          name: tutorial-archives
          path: archives

      - name: Unzip archive
        run: |
          unzip -q archives/${{ matrix.archive }} -d tutorial
        shell: bash

      - name: Set up compiler
        if: matrix.compiler == 'gcc' && matrix.os == 'ubuntu-latest'
        uses: egor-tensin/setup-gcc@v2
        with:
          version: latest
        # GCC is default on Linux, but this ensures it's available

      - name: Set up Clang
        if: matrix.compiler == 'clang'
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest

      - name: Set up MSVC
        if: matrix.compiler == 'msvc' && runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up mingw
        if: matrix.compiler == 'gcc' && matrix.os == 'windows-latest'
        uses: egor-tensin/setup-mingw@v3

      - name: Install Libraries (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

      - name: Build Gegelati (Linux/MacOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          git clone -b ${{ matrix.gegelati_version }} https://github.com/gegelati/gegelati.git lib/gegelati
          cd lib/gegelati/bin
          cmake .. -DBUILD_TESTING=OFF -DSKIP_DOXYGEN_BUILD=ON -DCMAKE_BUILD_TYPE=Release
          sudo cmake --build . --target install --parallel $(nproc)
        shell: bash

      - name: Download Gegelati neutral build (Windows)
        if: matrix.os == 'windows-latest' && matrix.gegelati_version == 'develop'
        env:
          SELECTED_COMPILER: ${{ matrix.compiler == 'msvc' && matrix.compiler || matrix.compiler == 'gcc' && 'mingw' || matrix.compiler }}
        run : |
          cd tutorial/gegelati-tutorial/lib
          curl --output gegelatilib.zip https://gegelati.github.io/neutral-builds/gegelatilib-${{env.SELECTED_COMPILER}}-latest-develop.zip
          unzip gegelatilib.zip

      - name: Configure CMake project
        run: |
          mkdir -p tutorial/build
          cmake -G "${{ env.CMAKE_GENERATOR }}" -S tutorial/gegelati-tutorial -B build -DTESTING=ON
        env:
          CC: ${{ matrix.compiler == 'gcc' && 'gcc' || matrix.compiler == 'clang' && 'clang' || '' }}
          CXX: ${{ matrix.compiler == 'gcc' && 'g++' || matrix.compiler == 'clang' && 'clang++' || '' }}
        shell: bash

      - name: Build manual-control target
        run: |
          cmake --build build --config Release --target manual-control --parallel $(nproc)
        shell: bash

      - name: Build and run tpg-training target
        if: matrix.archive != 'gegelati-tutorial.zip'
        run: |
          sed -i 's/"nbGenerations": [0-9]*/"nbGenerations": 4/' tutorial/gegelati-tutorial/params.json
          if [[ "${{ matrix.compiler }}" = "gcc" && "${{ matrix.os }}" = "windows-latest" ]]; then
            # Put compiler's mingw64 bin in PATH for dlls, otherwise git bash's own mingw64 is used and dlls are not compatible
            export PATH="/c/ProgramData/mingw64/mingw64/bin:$PATH"
          fi
          cmake --build build --config Release --target tpg-training --parallel $(nproc)
          cd build && ./Release/tpg-training | tee -a $GITHUB_STEP_SUMMARY  # cd needed for windows dll 
        shell: bash